import{collection,doc,getDoc,getDocs,query,where,addDoc,setDoc,updateDoc,deleteDoc,Timestamp,type DocumentData,type QueryConstraint}from'firebase/firestore';import{db}from'../firebaseConfig';import{ResourcePermission,ResourceType,ShareRecord,Visibility,User}from'../types';
export const RESOURCE_COLLECTIONS:Record<ResourceType,string>={document:'documents',task:'tasks',project:'projects',meeting:'meetings',client:'clients',followUp:'followUps',knowledge:'knowledge',report:'reports'};
export function resourceRoute(type:ResourceType,id:string){const map:Record<ResourceType,string>={document:'documents',task:'tasks',project:'projects',meeting:'meetings',client:'clients',followUp:'follow-ups',knowledge:'knowledge',report:'reports'};return`/${map[type]}/${encodeURIComponent(id)}`}
export function resourceUrl(type:ResourceType,id:string){return resourceRoute(type,id)} export function resourcePath(type:ResourceType,id:string){return`${RESOURCE_COLLECTIONS[type]}/${id}`}
export function normalizeUsername(value:string){return value.trim().toLowerCase().replace(/^@/,'')} export function isValidUsername(value:string){return/^[a-z0-9_]{3,30}$/.test(normalizeUsername(value))}
export function canReadResource(resource:Partial<{ownerId:string;visibility:Visibility;sharedWith:Record<string,ResourcePermission>}>,uid:string){return resource.ownerId===uid||resource.visibility==='workspace'||(resource.visibility==='shared'&&!!resource.sharedWith?.[uid])}
export function canWriteResource(resource:Partial<{ownerId:string;visibility:Visibility;sharedWith:Record<string,ResourcePermission>}>,uid:string){return resource.ownerId===uid||(resource.visibility==='shared'&&resource.sharedWith?.[uid]==='write')}
export async function findUserByUsername(username:string){const snap=await getDocs(query(collection(db,'users'),where('username','==',normalizeUsername(username))));return snap.empty?null:({id:snap.docs[0].id,...snap.docs[0].data()}as User)}
export async function isConnected(userA:string,userB:string){const a=await getDocs(query(collection(db,'connections'),where('requesterId','==',userA),where('recipientId','==',userB),where('status','==','accepted')));if(!a.empty)return true;const b=await getDocs(query(collection(db,'connections'),where('requesterId','==',userB),where('recipientId','==',userA),where('status','==','accepted')));return!b.empty}
export async function shareResource(input:{resourceType:ResourceType;resourceId:string;ownerId:string;recipientUserId:string;permission:ResourcePermission;expiresAt?:string}){if(input.ownerId===input.recipientUserId)throw new Error('The owner does not need a share.');if(!(await isConnected(input.ownerId,input.recipientUserId)))throw new Error('Only accepted connections can receive normal resource shares.');const now=new Date().toISOString();const ref=await addDoc(collection(db,'shares'),{...input,status:'active',createdAt:now,updatedAt:now});const resourceRef=doc(db,RESOURCE_COLLECTIONS[input.resourceType],input.resourceId);const resource=await getDoc(resourceRef);if(resource.exists()){const data=resource.data();await updateDoc(resourceRef,{visibility:'shared',sharedWith:{...(data.sharedWith||{}),[input.recipientUserId]:input.permission},updatedAt:now,updatedBy:input.ownerId})}await createNotification(input.recipientUserId,'share',`A ${input.resourceType} was shared with you.`,input.resourceType,input.resourceId);await logActivity(input.resourceType,input.resourceId,'shared',input.ownerId,`Shared with ${input.recipientUserId} (${input.permission}).`);return ref.id}
export async function revokeShare(shareId:string,actorId:string){const shareRef=doc(db,'shares',shareId),snap=await getDoc(shareRef);if(!snap.exists())throw new Error('Share not found.');const share=snap.data()as ShareRecord;if(share.ownerId!==actorId)throw new Error('Only the owner can revoke this share.');await updateDoc(shareRef,{status:'revoked',updatedAt:new Date().toISOString()});const resourceRef=doc(db,RESOURCE_COLLECTIONS[share.resourceType],share.resourceId),resource=await getDoc(resourceRef);if(resource.exists()){const sharedWith={...(resource.data().sharedWith||{})};delete sharedWith[share.recipientUserId];await updateDoc(resourceRef,{sharedWith:Object.keys(sharedWith).length?sharedWith:{},visibility:Object.keys(sharedWith).length?'shared':'private',updatedAt:new Date().toISOString(),updatedBy:actorId})}await createNotification(share.recipientUserId,'share_revoked','Your access to a Hub-Mind resource was revoked.',share.resourceType,share.resourceId);await logActivity(share.resourceType,share.resourceId,'share_revoked',actorId,`Access revoked for ${share.recipientUserId}.`)}
export async function logActivity(entityType:ResourceType,entityId:string,action:string,userId:string,details:string){await addDoc(collection(db,'activityLogs'),{entityId,entityType,action,userId,details,createdAt:new Date().toISOString()})} export async function createNotification(userId:string,type:string,message:string,resourceType?:ResourceType,resourceId?:string){await addDoc(collection(db,'notifications'),{userId,type,message,read:false,resourceType,resourceId,createdAt:new Date().toISOString()})}
export async function deleteResource(type:ResourceType,id:string,actorId:string){const ref=doc(db,RESOURCE_COLLECTIONS[type],id),snap=await getDoc(ref);if(!snap.exists())return;if(snap.data().ownerId!==actorId)throw new Error('Only the resource owner can delete this resource.');await deleteDoc(ref);await logActivity(type,id,'deleted',actorId,'Resource permanently deleted.')}
export async function queryOwnedResources<T extends DocumentData>(type:ResourceType,ownerId:string,...constraints:QueryConstraint[]){const snap=await getDocs(query(collection(db,RESOURCE_COLLECTIONS[type]),where('ownerId','==',ownerId),...constraints));return snap.docs.map(d=>({id:d.id,...d.data()}as T))}
export async function saveResource(type:ResourceType,id:string,data:Record<string,unknown>,actorId:string){const ref=doc(db,RESOURCE_COLLECTIONS[type],id),existing=await getDoc(ref),now=new Date().toISOString();if(existing.exists()&&existing.data().ownerId!==actorId&&!canWriteResource(existing.data(),actorId))throw new Error('You do not have write access to this resource.');await setDoc(ref,{...data,updatedAt:now,updatedBy:actorId},{merge:true})}
export function toIso(value:unknown){if(value instanceof Timestamp)return value.toDate().toISOString();if(value instanceof Date)return value.toISOString();return typeof value==='string'?value:new Date().toISOString()} export function isExpired(expiresAt?:string){return!!expiresAt&&new Date(expiresAt).getTime()<=Date.now()}
